# Generated by Django 4.0.4 on 2022-06-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtext', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='efile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etext', models.FileField(upload_to='')),
                ('ekey', models.CharField(max_length=20)),
            ],
        ),
    ]
