# Generated by Django 4.0.4 on 2022-06-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfile',
            name='dtext',
            field=models.FileField(upload_to='Files/'),
        ),
        migrations.AlterField(
            model_name='efile',
            name='etext',
            field=models.FileField(upload_to='Files/'),
        ),
    ]
