# Generated by Django 4.0.4 on 2022-06-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_dfile_dtext_alter_efile_etext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfile',
            name='dtext',
            field=models.FileField(default=None, null=True, upload_to='Files/'),
        ),
        migrations.AlterField(
            model_name='efile',
            name='etext',
            field=models.FileField(default=None, null=True, upload_to='Files/'),
        ),
    ]
